version: '3' # Docker Compose バージョンに対応するファイルバージョンを指定
services:
  app:
    build:
      # ビルドの起点となるパスとしてカレントディレクトリを指定
      context: .
      dockerfile: container/fastAPI/Dockerfile
    container_name: fastApi
    working_dir: /fastApi
    ports:
      # localhost の 8000 ポートでアクセスできるようにする
      - '8000:8000'
    volumes:
      - .:/fastApi
    command: ['uvicorn', 'main:app', '--host', '0.0.0.0', '--reload']
