# Docker Compose バージョンに対応するファイルバージョンを指定
version: '3'
services:
  app:
    build:
      # ビルドの起点となるパスとしてカレントディレクトリを指定
      context: .
      dockerfile: container/fastAPI/Dockerfile
      # Dockerfileの引数としてWORKDIRのパスを作成
      args:
        SOURCE_DIR: /fastApi
    container_name: fastApi
    ports:
      # localhost の 8000 ポートでアクセスできるようにする
      - '8000:8000'
    volumes:
      # メインプログラムファイルをコンテナにマウント
      - .:/fastApi
      # .venv先をマウントして、インストール時間の短縮を図る
      - ${VENV_CACHE_DIR:-venv}:/fastApi/.venv
    command: ['poetry', 'run', 'uvicorn', 'api.main:app', '--host', '0.0.0.0', '--reload']

volumes:
  # poetryのvenvをキャッシュするボリューム
  venv:
